[tool.pyright]
include = ["backend", "src"]
venvPath = "."
venv = ".venv"
reportMissingImports = false
reportMissingModuleSource = false
reportUndefinedVariable = false
typeCheckingMode = "standard"

[tool.ruff.lint]
select = ["I"]
fixable = ["I"]

[tool.yamllint.rules]
line-length = { max = 200 }
quoted-strings = "disable"
