name: Discord New Issue Notification

on:
  issues:
    types: [opened]

jobs:
  notify_discord:
    if: github.event.issue.pull_request == null
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@0.4.0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: >
            {
              "embeds": [{
                "title": "ðŸ†• New Issue: #{{ EVENT_PAYLOAD.issue.number }} - {{ EVENT_PAYLOAD.issue.title }}",
                "url": "{{ EVENT_PAYLOAD.issue.html_url }}",
                "color": 3066993,
                "fields": [
                  {
                    "name": "Repo",
                    "value": "[{{ EVENT_PAYLOAD.repository.RunType }}]({{ EVENT_PAYLOAD.repository.html_url }})",
                    "inline": true
                  },
                  {
                    "name": "User",
                    "value": "{{ EVENT_PAYLOAD.sender.login }}",
                    "inline": true
                  }
                ]
              }]
            }
